### ISSUE TITLE
unable to setup the codebase, stuck on PyTorch3D installation

### ISSUE THREAD

**Issue by forresti** [LIU-Yuxin/SyncMVD#16]
On Linux, I am struggling to get your code working.

```
conda create -n syncmvd python=3.8
conda activate syncmvd
```

I install PyTorch myself, to ensure it has the PyTorch version and CUDA version that is used in your repo:
```
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia
```

I commented pytorch out of requirements.txt and then ran this successfully:
```
pip install -r requirements.txt
```

## unable to uninstall PyTorch3D
Now is where I get stuck: installing PyTorch3D. I first try following this from your readme:
```
pip install https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt200/download.html
```

but it fails with this error:
```
Collecting https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt200/download.html

  Downloading https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt200/download.html (113 bytes)
  ERROR: Cannot unpack file /tmp/pip-unpack-_4lrruds/download.html (downloaded from /tmp/pip-req-build-2puc26gd, content-type: text/html); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-2puc26gd
```

I also tried building PyTorch3D from scratch:
```
git clone https://github.com/facebookresearch/pytorch3d.git
cd pytorch3d
pip install -e .
```
This fails with the following error:
```
Obtaining file:///home/ubuntu/SyncMVD/pytorch3d                                                                     
  Preparing metadata (setup.py) ... error                                                                           
  error: subprocess-exited-with-error                                                                               
                                                                                                                    
  × python setup.py egg_info did not run successfully.                                                              
  │ exit code: 1                                                                                                    
  ╰─> [8 lines of output]                                                                                           
      Traceback (most recent call last):                                                                            
        File "<string>", line 2, in <module>                                                                        
        File "<pip-setuptools-caller>", line 34, in <module>                                                        
        File "/home/ubuntu/SyncMVD/pytorch3d/setup.py", line 17, in <module>                                        
          from torch.utils.cpp_extension import CppExtension, CUDA_HOME, CUDAExtension                              
        File "/home/ubuntu/anaconda3/envs/syncmvd2/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]                                         
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/ubuntu/anaconda3/envs/syncmvd2/lib/python3.8/site-packages/pkg_resources/__init__.py)
      [end of output]         
```

Are there any suggestions for how to get this working? Thanks!

**Comment by LIU-Yuxin** [comment]
I just checked the pytorch3d repo and updated the pip installation command with extra options, it should be working using the new one in the current readme.

**Comment by forresti** [comment]
I tried your new command:

```
conda create -n syncmvd python=3.8
conda activate syncmvd
pip install -r requirements.txt
pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt200/download.html
```


The new error when installing PyTorch3D is:
```
Looking in links: https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt200/download.html
Collecting pytorch3d
  Downloading https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt200/pytorch3d-0.7.3-cp38-cp38-linux_x86_64.whl (72.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 MB 296.2 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of pytorch3d to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement fvcore (from pytorch3d) (from versions: none)
ERROR: No matching distribution found for fvcore
```

I was able to solve it by following the fvcore readme to install fvcore, then trying again to (successfully) install pytorch3d:

```
 conda install -c fvcore -c iopath -c conda-forge fvcore 

pip install --no-index --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu117_pyt200/download.html
```

And now the command in your readme works!
```
 python run_experiment.py --config ./data/face/config.yaml
```


![textured_views_rgb](https://github.com/LIU-Yuxin/SyncMVD/assets/2020010/8c7f8859-d954-4846-8ff9-24ca74e9d868)
